version: 1.0.{build}

image: Visual Studio 2015

branches:
  only:
    - main
skip_tags: true

platform: Any CPU
configuration: Release

build:
  publish_core_console: true
  verbosity: minimal

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

artifacts:
  - path: logs