version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_core_console: true
  parallel: true
  verbosity: minimal
before_build:
  - cd src/
  - nuget restore
deploy:
- provider: GitHub
  auth_token:
    secure: uMCpBhD4x2qomdqzfflWtqe9NdRtS3EOw6CSEEgi7jcPUaDxrBDNGDDVP4myp0ec
  force_update: true
  on:
    branch: main